### ISSUE TITLE
Use of open public streams from Colombia

### ISSUE THREAD

**Issue by iemejia** [diegofn/wiiego-xbmc-addons#1]
Hi,
I just picked some open Colombian TV streams and created this project:
https://github.com/iemejia/streamingcolombia
Do you think you can use it (or integrate it) in yours ?
If you need me to fix something so it can work with yours just tell me.
I will keep working on adding some of the missing channels soon.

**Comment by juanMFC15** [comment]
Tengo la vercion 1.0.5 muchos canales no funcionan, RCN HD, RCN HD Oficial, CityTV y otros mas, lo uso desde el Amazon Firestick baje este add on desde Super Repo en http://srp.nu alguna idea de como hacer que funcionen ??
