### ISSUE TITLE
Excelente Addon... "Es posible agregar La Kalle TV?"

### ISSUE THREAD

**Issue by soycamiloypunto** [diegofn/wiiego-xbmc-addons#11]
Es posible agregar un nuevo canal: La Kalle TV?

http://lakalle.bluradio.com/noticias/llego-la-kalle-tdt-aprende-sintonizar-la-mandamas-en-tu-tv-1237

**Comment by diegofn** [comment]
Hola, seria interesante agregar una sección de emisoras, pero aplicaciones como TuneIn ya las tiene.

Saludos.

**Comment by soycamiloypunto** [comment]
Tunein radio funciona muy mal en tvbox ya que la navegación de la aplicación es táctil y no por control. Por eso sería útil tenerlas aquí mismo.

Enviado desde mi iPhone

**Comment by diegofn** [comment]
Lo tendré en cuenta para una futura versión!

**Comment by diegofn** [comment]
Hola, en la nueva versión le he agregado algunas emisoras de radio de Colombia. Pruébalo y me cuentas.
