### ISSUE TITLE
Es posible agregar a la lista de canales el nuevo canal infantil tacho pistacho?

### ISSUE THREAD

**Issue by soycamiloypunto** [diegofn/wiiego-xbmc-addons#12]
Buen día, uso todos los días KODI y el excelente addon, nosotros vivimos en silvania y en la dorada y mi familia y varios amigos disfrutamos de tu addon. simplemente excelente... aunque tenemos problemas con la señal de caracol y rcn por que hay muchos links pero la mayoría no funcionan correctamente, ojala pudieras solucionarlo pronto. también quisieramos saber si es posible que agregues el nuevo canal infantil de rcn tacho pistacho que está disponible en la tdt y tiene señal en vivo por internet: http://www.tachopistacho.com sería excelente poder tener un canal infantil las 24 horas para nuestros hijos.. un saludo y gracias por tan buen trabajo.

**Comment by diegofn** [comment]
Hola, en la versión 1.4.4. ya se incluyó, esta antes de los canales de noticias.
