### ISSUE TITLE
Excelente addon pero últimamente no funcionan las peliculas

### ISSUE THREAD

**Issue by soycamiloypunto** [diegofn/wiiego-xbmc-addons#14]
Hola, soy FAN de este addon, lo tengo instalado en todos los tvbox propios y de conocidos, el servicio es excelente, además de las series y peliculas que ofreces. pero los últimos dias no funcionan las peliculas, he intentado ver mas de 5 peliculas no funciona, si pudieses verlos, y revisarlos estaría muy agradecido....

Feliz dia.

Detalles del error al tratar de reproducir: Reproducción de lista abortada, uno o más elementos fallaron al reproducir. revise el registro par aobtener as información a cerca de este mensaje.

Ver las últimas lineas del log de kodi adjunto.

[kodi.log](https://github.com/diegofn/wiiego-xbmc-addons/files/1778834/kodi.log)

**Comment by diegofn** [comment]
Hola @soycamiloypunto, te cuento que el hoster donde tenía las peliculas lo borraron. Así que el usuario las está volviendo a subir.

Llevo reconstruido hasta el 2010 y algunas recientes. Te pido un poco de paciencia, son muchas peliculas, si encuentras peliculas Colombianas que no están en el catálogo, te pido que las compartas.
