### ISSUE TITLE
Canales que no funcionan 

### ISSUE THREAD

**Issue by juanMFC15** [diegofn/wiiego-xbmc-addons#4]
Tengo la vercion 1.0.5 muchos canales no funcionan, RCN HD, RCN HD Oficial, CityTV y otros mas solo se quedan en "working" pero nunca inician, de hecho, lo bloquean y toca reiniciar kodi ... lo uso desde el Amazon Firestick baje este add on desde Super Repo en http://srp.nu alguna idea de como hacer que funcionen ??

**Comment by diegofn** [comment]
Hola, 

Infortunadamente, no hay links públicos de CityTV, si encuentras uno, compártelo. RCN y RCN HD funcionan bien desde Colombia, si estas fuera, de pronto te toca usar un proxy

**Comment by juanMFC15** [comment]
canales como WinSports usan proxy pero no se como hacer para que los otros lo hagan

**Comment by diegofn** [comment]
Hola, actualice algunos links, por favor prueba desde tu país y me comentas como te fue!

**Comment by juanMFC15** [comment]
mahora me funcionan muy bien, pero el problema cambio, ahora los que no funcionan son los que usualmente funcionaban, como winsports

**Comment by ivanchorojo** [comment]
hola, solo quiero agradecer al autor de este repo, de verdad esta genial ojala dure por siempre este Proyecto.

**Comment by diegofn** [comment]
Gracias
