### ISSUE TITLE
Colombia TV si audio-no video 

### ISSUE THREAD

**Issue by neroca** [diegofn/wiiego-xbmc-addons#5]
Instale codi en una tablet lenovo a7-20f. Todo funciona menos Colombia TV. Es una Android 4.4.2 kodi instalacion Jarvis. Intente version anterior de kodi (15.2) y el mismo problema. 
 Escucho audio no video. La misma configuration en otros dispositivos Android funciona bien.

**Comment by diegofn** [comment]
Hola, Te instaló o no en la Lenovo? y cual canal no puedes ver?

**Comment by neroca** [comment]
Hola Diego, si el add-on instalo, pero no sE puede ver ningun canal de Colombia TV. En todos sE escuchas el audio pero no hay video. Gracias por su ayuda.
