### ISSUE TITLE
Senal Colombia no funciona

### ISSUE THREAD

**Issue by matzoi** [diegofn/wiiego-xbmc-addons#6]
[log.txt](https://github.com/diegofn/wiiego-xbmc-addons/files/211616/log.txt)

Podrias por Favor ayudarme a sintonizar el canal de  Senal Colombia?  Cuando abro este canal, no funciona. Dicho canal funciono en dias anteriores, pero ahora ya no funciona. Puedo ver en el log esta linea...
ERROR: Playlist Player: skipping unplayable item: 0, path [http://173.192.25.13:1935/TELE/smil:senalcolombia.smil/canalesdelpueblotv.m3u8]

Uso Jarvis 16.0 en Windows 10.

**Comment by diegofn** [comment]
Link arreglado, prueba por favor

**Comment by matzoi** [comment]
Ya funciona.  Muchas gracias por su efuerzo a mantener la excelencia de su programa..
