### ISSUE TITLE
Reporte de pruebas ver 1.3.1

### ISSUE THREAD

**Issue by fantore** [diegofn/wiiego-xbmc-addons#7]
Gracias Diego por este addon, lo valoro y uso mucho.

** Estoy fuera de colombia

Acabo de actualizar a 1.3.1. Corre bien en kodi jarvis y kodis kripton alpha que compile hoy.

Issues con canales que no funcionan.

Caracol -- segundo item
RCN HD Oficial
RCN HD
RCN (mips)
RCN Radio TV requiere livestream, se instala y no funciona
winsports f4mtester required,,  no funciona. Como se instala f4mtester??
senal colombia primer item
citytv
canal 13
canal capital primer item
Telepacifico
ntn24
ntn dice video no disponibleen youtube
une armenia
une eventos
Telesur
senal institucional sd
senal institucional
zoom

gracias por tu gentil ayuda y en lo que te pueda ayudar a testear con gusto,

**Comment by diegofn** [comment]
Buenos días gracias por las pruebas.

Algunos comentarios:
RCN Oficial: Al parecer este link solo funciona desde Colombia :S
RCN Radio TV: Este streaming se activa cuando ellos hacen streaming generalmente de Lunes a Viernes de 6 a 7am.
WinSports f4mtester ya no funciona, lo mantengo por si revive.
Señal Colombia lo mantengo porque es el stream que prestaba la empresa anterior, de pronto algún día regresa.
CityTV: No hay links publicos.

De nuevo, gracias por el feedback, si encuentras links o página de esas que tienen mucha publicidad pásalas, de pronto funciona.

**Comment by diegofn** [comment]
Hola, 

Gracias a tu revisión he eliminado y actualizado algunos canales que aunque son de poca demanda no funcionaban. Gracias de nuevo por el feedback.
