### ISSUE TITLE
Reporte de pruebas ver 1.3.1 sobre actualizacion notificada

### ISSUE THREAD

**Issue by fantore** [diegofn/wiiego-xbmc-addons#8]
Hola Diego buenas noches.

Gracias por comunicarme de los cambios.

Hice este test,  fuera de Colombia con kodi Ver 15.2  Ubuntu-Mate

Entenderia que canbiaste los canales en el archivo *.json del folder en dropbox, pues la version del addon no se actualizo.

Canales que NO funcionan

CARACOL HD  segunda opcion
CARACOL (janjua) - funcionaba antes.
CARACOL (mips) segunda opcion
RCN HD oficial
RCN HD
RCN (janjua) - las dos opciones funcionaban antes.
RCN  (mips)
WinSports (f4mtester required)
CityTV
Canal Capital Primera opcion
NTN24 las dos opcioies

El resto esta ok.  RCN es clave tenerlo.....

Gracias por el addon y tu trabajo, Lo valoro mucho.

Sigo pendiente en ayudarte.

Cordial Saludo,

BTW, el pdf de las revistas tambien las uso mucho.... a la espera de la ultima SOHO.

Gracias de nuevo

**Comment by diegofn** [comment]
Links actualizados, gracias por la retro alimentación
