### ISSUE TITLE
Excelente Addon NUNCA FALTA EN MI KODI

### ISSUE THREAD

**Issue by soycamiloypunto** [diegofn/wiiego-xbmc-addons#9]
Agradezco el trabajo. Por fin puedo ver en HD todos los canales colombianos. Gracias por su esfuerzo. Solo quisiera que si pudieras por favor agregar al Canal Uno ahora su streaming es público... http://canal1.com.co/shows-vivo/senal-en-vivo/ sería excelente agregarlo a su parrilla de canales

**Comment by diegofn** [comment]
Buenos días,

El link ya fue agregado, por favor pruebalo y me cuentas. Gracias por utilizar el addon.

**Comment by soycamiloypunto** [comment]
Gracias!!! Fucilando !!! Muchas gracias 

Enviado desde mi iPhone
